maintenance:
  status: true
  kick-reason: "&cServer is currently in maintenance.\n&cGo back Later"
  accepted-players: {}
  motd:
    line-1: "&f&lChunkly &7┃ &cchunkly.org/updates"
    line-2: "&eCheck our page for updates."

